variable "region" {
  description = "Region label used for the S3 client (LocalStack ignores it, but the SDK needs one)."
  type        = string
  default     = "us-east-1"
}

variable "localstack_endpoint" {
  description = "LocalStack edge endpoint used by Terraform/CLI (path-style)."
  type        = string
  default     = "http://localhost:4566"
}

variable "sdk_s3_endpoint" {
  description = <<-EOT
    Endpoint the Maven plugin's Java SDK should use. Uses LocalStack's virtual-host
    domain so <bucket>.<host> resolves to 127.0.0.1. Surfaced as an output for the build.
  EOT
  type        = string
  default     = "http://s3.localhost.localstack.cloud:4566"
}

variable "localstack_image" {
  description = "LocalStack container image."
  type        = string
  default     = "localstack/localstack:3"
}

variable "container_name" {
  description = "Name for the LocalStack container Terraform manages."
  type        = string
  default     = "tls-localstack"
}

variable "bucket_name" {
  description = "S3 bucket to create and hold the keystore."
  type        = string
  default     = "mule-tls-bucket"
}

variable "key" {
  description = "S3 object key for the keystore (matches the app's tls.key)."
  type        = string
  default     = "mule-app/dev/keystore.jks"
}

variable "key_alias" {
  description = "Keystore alias generated by keytool."
  type        = string
  default     = "mule-tls"
}

variable "store_password" {
  description = "Demo keystore/store password. Throwaway — never a real secret."
  type        = string
  default     = "changeit"
}

variable "key_password" {
  description = "Demo key password. Throwaway — never a real secret."
  type        = string
  default     = "changeit"
}
